### ISSUE TITLE
Register User

### ISSUE THREAD

**Issue by izacristina** [fga-gpp-mds/2016.2-WikiLegis#1]

**Comment by RochaCarla** [comment]
Fiquem atentos... Issue é ágil :P

**Comment by izacristina** [comment]
@RochaCarla Dá uma olhada no nosso Política de Utilização do Git, https://github.com/fga-gpp-mds/2016.2-WikiLegis/wiki/Plano-de-Gerenciamento-de-Configura%C3%A7%C3%A3o, as issues só servem para que o grupo saiba que branches criar e mapear os commits com o caso de uso. Meu GPP também fazia assim, agora não pode mais?
