### ISSUE TITLE
TS11 - Melhorar ACC

### ISSUE THREAD

**Issue by izacristina** [fga-gpp-mds/2016.2-WikiLegis#22]
**Eu, como** desenvolvedor 
**Desejo** refatorar o código
**Para** melhorar a métrica de ACC (Média de Conexões Aferentes)

Responsáveis: @lucasBrilhante, @josutk 

**Critérios de aceitação**
- A média deve estar abaixo de 2

**Tarefas**
- [x]  Refatorar a DAOUtilies

- [ ] Segment

- [ ] Bill

**Comment by thiagonf** [comment]
Após estudar o artigo(http://bdm.unb.br/bitstream/10483/11317/1/2015_MarcosRonaldoPereiraJunior.pdf) referente a API do próprio Android, foi visto que valores do ACC para percentil 95 podem chegar até 26. Tomando como parâmetro estes dados, os valores obtidos após a refatoração do código mostram que foram obtidos uma melhora significativa na qualidade de acoplamento.
